const lang = {
  LANG01: "Remember the ID",
  LANG02: "Sign Up",
  LANG03: "login",
  LANG04: "find password",
  LANG05: "Please enter all of the values",
  LANG06: "Invalid account information",
  LANG07: "Country selection",
  LANG08: "ID inputs for 6 digits including English + numbers",
  LANG09: "Search",
  LANG10: "Number + Include special characters, input for more than 6 digits",
  LANG11: "The password is different.",
  LANG12: "Bank selection",
  LANG13: "Select local camp",
  LANG14: "go back",
  LANG15: "Account Holder",
  LANG16: "Account Number",
  LANG17: "Career",
  LANG18: "Zip code",
  LANG19: "Detailed Address",
  LANG20: "Membership Search",
  LANG21: "Please enter your membership.",
  LANG22: "Member ID",
  LANG23: "Membership name",
  LANG24: "select",
  LANG25: "Please select a country",
  LANG26: "Please proceed with your mobile phone certification first.",
  LANG27: "Normal subscription processed.",
  LANG28: "Duplicate ID.",
  LANG29: "This is a non-existent recommendation.",
  LANG30: "Invalid value input",
  LANG40: "Confirm",
  LANG41: "Certification",
  LANG42: "certification",
  LANG43: "Profile",
  LANG44: "name",
  LANG45: "e-mail",
  LANG46: "Second password",
  LANG47: "change",
  LANG48: "Change Password",
  LANG49: "Account information",
  LANG50: "save",
  LANG51: "Normally changed",
  LANG52: "No transfer password is not correct.",
  LANG53: "Contact your administrator",
  LANG54: "cash",
  LANG55: "Possible amount",
  LANG56: "Bonus history",
  LANG57: "date",
  LANG58: "Contents",
  LANG59: "bonus",
  LANG60: "leftover",
  LANG61: "point",
  LANG62: "rank",
  LANG63: "stock",
  LANG64: "My bill",
  LANG65: "Total Overview",
  LANG66: "Expected bonus",
  LANG67: "Activity guard",
  LANG68: "Notice",
  LANG69: "View list",
  LANG70: "title",
  LANG71: "Organization chart",
  LANG72: "suggestion",
  LANG73: "Deposit Account Guide",
  LANG74: "product name",
  LANG75: "Product amount",
  LANG76: "won",
  LANG77: "Application amount",
  LANG78: "Total deposit amount",
  LANG79: "Deposit information",
  LANG80: "Deposit",
  LANG81:
    "If the deposit name is different, it will not be processed. Please check again.",
  LANG82: "cancellation",
  LANG83: "Deposit",
  LANG84: "Purchase",
  LANG85: "Normal application processed.",
  LANG86: "Please enter quantity!",
  LANG87: "Please enter your deposit number",
  LANG88: "Purchase history",
  LANG89: "Package name",
  LANG90: "Lack of balance",
  LANG91: "Purchase date",
  LANG92: "state",
  LANG93: "note",
  LANG94: "Remittance",
  LANG95: "Transferable amount",
  LANG96: "Membership",
  LANG97: "Remittance",
  LANG98: "Transfer password",
  LANG99: "Application",
  LANG100: "It is a member that does not exist.",
  LANG101: "No transfer password is not correct.",
  LANG102: "stock",
  LANG103: "Stock Bonus History",
  LANG104: "Payment",
  LANG105: "Password",
  LANG106: "Apply for an inlet",
  LANG107: "The Password does not fit",
  LANG108: "Request for request",
  LANG109: "fees",
  LANG110: "Final elements",
  LANG111: "Checking the application",
  LANG112: "Application",
  LANG113: "Password",
  LANG114: "The initial password",
  LANG115: "no see.",
  LANG116: "verify password",
  LANG117: "Password is not right",
  LANG118: "Withdrawal status",
  LANG119: "Withdrawal application",
  LANG120: "Investment payment history",
  LANG121: "Make an investment payment",
  LANG122: "menu",
  LANG123: "account",
  LANG124: "Changing information",
  LANG125: "Social Security Number",
  LANG126: "Please enter your social security number",
};

module.exports = lang;
